---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testusr2-prod-app-pv
  namespace: stage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.146.0.4
    path: "/opt/NFS_SHARE/prod1/testusr2/data/app"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testusr2-prod-app-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
