---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-mysql-master-pv
  namespace: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.146.0.4
    path: "/opt/NFS_SHARE/prod1/prod_mysql_master"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-mysql-master-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
